"""Stoatworks Labs — About window data for WSM–WWB Bridge.

GENERATED by stoatworks-backend/scripts/sync-about.py on 2026-08-03. Do not
edit: the next sync overwrites it. The facts come from the website's
projects.json, which is the one place they are written down.

`version` here is a fallback read from this repo's own manifest at sync
time. Anything with a build step injects the real one at build time and
overrides this."""

from __future__ import annotations

NAME = "WSM\u2013WWB Bridge"
SLUG = "wsm-wwb-bridge"
HOOK = "Shure to Sennheiser, both ways"
LICENCE = "MIT"
GUIDE = "https://stoatworks-labs.com/software/wsm-wwb-bridge/guide/"
PAGE = "https://stoatworks-labs.com/software/wsm-wwb-bridge/"
REPO = "https://github.com/stoatworks-labs/wsm-wwb-bridge"
VERSION_FALLBACK = ""

ORG = "Stoatworks Labs"
HOME = "https://stoatworks-labs.com"
TAGLINE = "Open tools for the people who run the show."

# The canonical funding links, matching FUNDING.yml and the support footer.
FUNDING = [
    ("GitHub Sponsors", "https://github.com/sponsors/stoatworks-labs"),
    ("Ko-fi", "https://ko-fi.com/stoatworkslabs"),
    ("Patreon", "https://patreon.com/StoatworksLabs"),
    ("Liberapay", "https://liberapay.com/stoatworks-labs"),
]
